package org.example.UIComponents.forms;

import org.example.utils.visual.IconsEnum;
import org.example.utils.visual.ScalingHelper;

import javax.swing.*;
import javax.swing.plaf.FontUIResource;
import javax.swing.text.StyleContext;
import java.awt.*;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.util.Locale;


public class Credits extends JPanel {
    private JPanel panel;
    private JButton backButton;
    private JLabel title;
    private JLabel text;
    private JLabel text1;

    public Credits(JFrame frame) {
        frame.setTitle("Credits");
        panel.setPreferredSize(frame.getSize());
        try {
            backButton.addComponentListener(new ComponentAdapter() {
                @Override
                public void componentResized(ComponentEvent e) {
                    backButton.setIcon(IconsEnum.BACK_ICON.getImageIcon(90));
                }
            });

            backButton.addActionListener(_ -> {
                Menu menu = new Menu(frame);
                frame.setContentPane(menu);
                frame.revalidate();
                frame.repaint();
            });
        } catch (Exception e) {
            e.printStackTrace();
        }

        frame.addComponentListener(new ComponentAdapter() {
            @Override
            public void componentResized(ComponentEvent evt) {

                ScalingHelper.scaleComponent(frame.getSize(), Credits.this);

            }
        });

        add(panel);

    }



// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!



}
